Use pkg/errors.New instead of stdlib one
Exception: errors that are reused at multiple places. For those, we add
the stacktrace at the place at which they are returned using
errors.WithStack.